version: '3'

services:

  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres_data:
